default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-added-large-files
        stages: [ pre-commit ]
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
      - id: insert-license
        stages: [ pre-commit ]
        name: Insert license header in python files
        types_or: [ python ]
        args:
          - --license-filepath
          - .github/workflows/insert-license.txt
          - --use-current-year
          - --no-extra-eol
      - id: insert-license
        stages: [ pre-commit ]
        name: Insert license header in javascript and css files
        types_or: [ javascript, css ]
        args:
          - --license-filepath
          - .github/workflows/insert-license.txt
          - --comment-style
          - /*!| *| */
          - --use-current-year
          - --no-extra-eol
      - id: insert-license
        stages: [ pre-commit ]
        name: Insert license header in html files
        types_or: [ html ]
        args:
          - --license-filepath
          - .github/workflows/insert-license.txt
          - --comment-style
          - <!--|  ~|  -->
          - --use-current-year
          - --no-extra-eol
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.3.4
    hooks:
      - id: ruff
        stages: [ pre-commit ]
        name: Run python linter
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      - id: ruff-format
        stages: [ pre-commit ]
        name: Run python formatter
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        stages: [ commit-msg ]
        name: Check commit message style