services:
#  demo_202303_client_2:
#    build: .
#    tty: true
#    restart: on-failure
#    environment:
#      - DATASET_PATH=${DATASET_PATH}
#    volumes:
#      - ${DATASET_PATH}:${DATASET_PATH}
#    command: bash -c "demo_202303_client --clientId 2 --pcapBasePath ${DATASET_PATH}"
#  demo_202303_client_5:
#    build: .
#    tty: true
#    restart: on-failure
#    environment:
#      - DATASET_PATH=${DATASET_PATH}
#    volumes:
#      - ${DATASET_PATH}:${DATASET_PATH}
#    command: bash -c "demo_202303_client --clientId 5 --pcapBasePath ${DATASET_PATH}"
  model_aggr_server:
    build: .
    tty: true
    restart: on-failure
    ports:
      - "8003:8003"
    command: bash -c "model_aggr_server --dashboardURL 'http://dashboard:8000'"
  pred_aggr_server:
    build: .
    tty: true
    restart: on-failure
    ports:
      - "8002:8002"
    command: bash -c "pred_aggr_server --dashboardURL 'http://dashboard:8000'"
  eval_aggr_server:
    build: .
    tty: true
    restart: on-failure
    ports:
      - "8001:8001"
    command: bash -c "eval_aggr_server --dashboardURL 'http://dashboard:8000'"
  dashboard:
    build: .
    tty: true
    restart: on-failure
    ports:
      - "8000:8000"
    command: bash -c "dashboard"
