# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 5.0.1 on 2024-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_rename_sensordata_nodedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedata',
            name='address',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeData',
        ),
    ]
