# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 5.0.1 on 2024-01-31 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_accuracy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accuracy',
            name='address',
        ),
        migrations.RemoveField(
            model_name='accuracy',
            name='timestamp',
        ),
        migrations.DeleteModel(
            name='NodeData',
        ),
    ]
