# Generated by Django 5.0.1 on 2024-03-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_f1_precision_recall"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aggregation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agg_status", models.CharField(max_length=255)),
                ("agg_count", models.IntegerField()),
                ("agg_time", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
