# Copyright (C) 2028 DAI-Labor and others
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 5.0.1 on 2024-03-04 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0006_evaluation_node_last_connection"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("alert", "Alert"),
                        ],
                        max_length=10,
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                ("message", models.CharField(max_length=255, unique=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
