# Generated by Django 5.0.1 on 2024-03-04 23:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alerts"),
    ]

    operations = [
        migrations.RenameField(
            model_name="node",
            old_name="adress",
            new_name="address",
        ),
        migrations.RemoveField(
            model_name="node",
            name="last_connection",
        ),
    ]
