# Copyright (C) 2024 DAI-Labor and others
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
# Generated by Django 5.0.1 on 2024-03-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0008_rename_adress_node_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Metrics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("accuracy", models.FloatField()),
                ("f1", models.FloatField()),
                ("recall", models.FloatField()),
                ("precision", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Accuracy",
        ),
        migrations.DeleteModel(
            name="F1",
        ),
        migrations.DeleteModel(
            name="Precision",
        ),
        migrations.DeleteModel(
            name="Recall",
        ),
    ]
