name: of-ids
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.10
  - pip=23.2.1
  - python=3.11.4
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
      - absl-py==1.4.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - blinker==1.6.2
      - cachetools==5.3.1
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - click==8.1.7
      - dash==2.9.2
      - dash-core-components==2.0.0
      - dash-html-components==2.0.0
      - dash-table==5.0.0
      - flask==2.3.2
      - flatbuffers==23.5.26
      - gast==0.4.0
      - google-auth==2.22.0
      - google-auth-oauthlib==1.0.0
      - google-pasta==0.2.0
      - grpcio==1.57.0
      - h5py==3.9.0
      - idna==3.4
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - keras==2.13.1
      - libclang==16.0.6
      - lxml==4.9.3
      - lz4==4.3.2
      - markdown==3.4.4
      - markupsafe==2.1.3
      - numpy==1.24.3
      - oauthlib==3.2.2
      - opt-einsum==3.3.0
      - packaging==23.1
      - pandas==2.0.2
      - plotly==5.14.1
      - protobuf==4.24.1
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyshark==0.6
      - python-dateutil==2.8.2
      - pytz==2023.3
      - requests==2.31.0
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - six==1.16.0
      - tenacity==8.2.3
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.1
      - tensorflow==2.13.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.33.0
      - termcolor==2.3.0
      - typing-extensions==4.5.0
      - tzdata==2023.3
      - urllib3==1.26.16
      - werkzeug==2.3.7
      - wrapt==1.15.0
