# Generated by Django 5.0.1 on 2024-01-31 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0002_remove_node_accuracy_remove_node_f1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SensorData',
            new_name='NodeData',
        ),
    ]
