# Generated by Django 5.0.1 on 2024-01-31 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('view', '0003_rename_sensordata_nodedata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodedata',
            name='address',
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.DeleteModel(
            name='NodeData',
        ),
    ]
