name: CI-fast

on:
  pull_request:
    branches-ignore: [ main, develop ]
  push:
    branches-ignore: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff
      - name: Run Ruff Check
        run: ruff check --output-format=github .
      - name: Run Ruff Format
        run: ruff format --check .
        if: success() || failure()