name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: 'pip'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Run tests with pytest and coverage
        run: |
          pytest --cov=daisy --cov-report=xml --integration-cover
          genbadge coverage -i coverage.xml -o .github/workflows/coverage-badge.svg
        if: success() || failure()
      - name: Apply changes with pre-commit-ci-lite
        uses: pre-commit-ci/lite-action@v1.1.0
        if: success() || failure()