name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov
      - name: Run Pre-Commit
        uses: pre-commit/action@v3.0.1
      - name: Apply Changes
        uses: pre-commit-ci/lite-action@v1.0.2
        if: success() || failure()
      - name: Run Tests with pytest
        run: |
          pytest tests.py --doctest-modules --junitxml=junit/test-results.xml 
          --cov=com --cov-report=xml --cov-report=html